import {
  MAX_PUBLIC_JOB_CLAUSES,
  MAX_PUBLIC_JOB_COMPRESSED_FORMULA_BYTES,
  MAX_PUBLIC_JOB_ENCODED_FORMULA_BYTES,
  MAX_PUBLIC_JOB_LITERAL_OCCURRENCES,
  MAX_PUBLIC_JOB_VARIABLES,
} from "../../../shared/public-jobs";

export const MAX_COMPRESSED_FORMULA_BYTES = MAX_PUBLIC_JOB_COMPRESSED_FORMULA_BYTES;
export const MAX_ENCODED_FORMULA_BYTES = MAX_PUBLIC_JOB_ENCODED_FORMULA_BYTES;
export const MAX_LITERAL_OCCURRENCES = MAX_PUBLIC_JOB_LITERAL_OCCURRENCES;
export const MAX_CLAUSES = MAX_PUBLIC_JOB_CLAUSES;
export const MAX_VARIABLES = MAX_PUBLIC_JOB_VARIABLES;

// Compressed DIMACS input is bounded independently from HiveCnfV1 so comments
// and whitespace cannot expand without limit before canonicalization.
export const MAX_DECOMPRESSED_DIMACS_BYTES = 32 * 1024 * 1024;

export const SOLVER_CLAUSE_BATCH_INTS = 64 * 1024;
